export const BLOOM_PATCH_CONFIG = Object.freeze({
  // Cursor attention is measured in world-space ground units.
  ATTENTION_RADIUS: 2.65,
  ATTENTION_GAIN_RATE: 0.85,
  ATTENTION_DECAY_RATE: 0.075,
  DECAY_THRESHOLD: 0.2,
  ATTENTION_GRACE_DURATION: 3.2,

  // A patch remains fully present for at least this long, even when the
  // pointer never returns to it.
  MIN_PATCH_LIFETIME: 8,
  DECAY_DURATION: 4.6,

  // A single fixed Points pool renders sampled flower silhouettes, flower
  // centers, and the restrained patch aura. No ambient dust cloud is used.
  PARTICLE_POOL_CAPACITY: 8192,
  FLOWER_PARTICLE_SAMPLE_LIBRARY_SIZE: 320,
  FLOWER_PARTICLE_SAMPLE_COUNT: 18,
  FLOWER_PARTICLE_ACTIVE_RATIO: 0.82,
  ACTIVE_PATCH_ENHANCED_RATIO: 0.28,
  FLOWER_PARTICLE_BIRTH_DURATION: 1.45,
  FLOWER_PARTICLE_BIRTH_OPACITY: 0.78,
  FLOWER_PARTICLE_IDLE_OPACITY: 0.09,
  FLOWER_PARTICLE_ATTENDED_OPACITY: 0.34,
  FLOWER_PARTICLE_DECAY_OPACITY: 0.82,
  FLOWER_PARTICLE_IDLE_FADE_DURATION: 0.62,
  FLOWER_PARTICLE_DRIFT_AMOUNT: 0.014,
  FLOWER_PARTICLE_COLOR_VARIANCE: 0.08,
  FLOWER_PARTICLE_SIZE_MIN: 1.7,
  FLOWER_PARTICLE_SIZE_MAX: 3.7,
  FLOWER_CENTER_GLOW_INTENSITY: 0.2,
  FLOWER_CENTER_GLOW_RADIUS: 38,
  PATCH_GLOW_INTENSITY: 0.16,
  PATCH_GLOW_DURATION: 1.55,
  PATCH_GLOW_RADIUS_MIN: 108,
  PATCH_GLOW_RADIUS_MAX: 162,
  DECAY_EDGE_BREAKUP_AMOUNT: 0.38,
});
