export const BLOOM_PATCH_CONFIG = Object.freeze({
  // Cursor attention is measured in world-space ground units.
  ATTENTION_RADIUS: 2.65,
  ATTENTION_GAIN_RATE: 0.85,
  ATTENTION_DECAY_RATE: 0.075,
  DECAY_THRESHOLD: 0.2,
  ATTENTION_GRACE_DURATION: 3.2,

  // A patch remains fully present for at least this long, even when the
  // pointer never returns to it.
  MIN_PATCH_LIFETIME: 8,
  DECAY_DURATION: 4.6,

  // A single fixed Points pool renders sampled flower silhouettes, flower
  // centers, and the restrained patch aura. No ambient dust cloud is used.
  PARTICLE_POOL_CAPACITY: 12288,
  FLOWER_PARTICLE_SAMPLE_LIBRARY_SIZE: 512,
  FLOWER_PARTICLE_SAMPLE_COUNT: 40,
  FLOWER_PARTICLE_ACTIVE_RATIO: 0.9,
  ACTIVE_PATCH_ENHANCED_RATIO: 0.48,
  FLOWER_PARTICLE_CENTER_EMPHASIS: 1.6,
  FLOWER_PARTICLE_EDGE_SAMPLE_RATIO: 0.26,
  FLOWER_PARTICLE_BIRTH_DURATION: 0.9,
  FLOWER_PARTICLE_BIRTH_HOLD_DURATION: 0.4,
  FLOWER_PARTICLE_SETTLE_DURATION: 0.8,
  FLOWER_PARTICLE_BIRTH_OPACITY: 0.9,
  FLOWER_PARTICLE_IDLE_OPACITY: 0.16,
  FLOWER_PARTICLE_ATTENDED_OPACITY: 0.44,
  FLOWER_PARTICLE_DECAY_OPACITY: 0.88,
  FLOWER_PARTICLE_IDLE_FADE_DURATION: 0.55,
  FLOWER_PARTICLE_DRIFT_AMOUNT: 0.01,
  FLOWER_PARTICLE_COLOR_VARIANCE: 0.04,
  FLOWER_PARTICLE_SIZE_MIN: 0.8,
  FLOWER_PARTICLE_SIZE_MAX: 1.65,
  FLOWER_CENTER_GLOW_INTENSITY: 0.16,
  FLOWER_CENTER_GLOW_RADIUS: 15,
  PATCH_GLOW_INTENSITY: 0.045,
  PATCH_GLOW_DURATION: 1,
  PATCH_GLOW_RADIUS_MIN: 64,
  PATCH_GLOW_RADIUS_MAX: 92,
  DECAY_EDGE_BREAKUP_AMOUNT: 0.38,

  // The card stays subdued until the sampled point cloud has described the
  // flower, then becomes the quiet base layer of the hybrid rendering.
  FLOWER_CARD_REVEAL_DELAY: 0.5,
  FLOWER_CARD_REVEAL_DURATION: 0.95,
  FLOWER_CARD_DECAY_VITALITY_FLOOR: 0.2,
  FLOWER_CARD_DECAY_MIN_VISIBILITY: 0.06,
});
